services:
  frontend:
    build: .
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PORT=3000
